DROP DATABASE IF EXISTS first_proj;
CREATE DATABASE first_proj;
USE first_proj;

CREATE TABLE information (
	iid INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	regDate DATETIME NOT NULL,
	memberId INT UNSIGNED NOT NULL,
	`name` CHAR(100) NOT NULL,
	sex CHAR(2) NOT NULL,
	age INT(3) NOT NULL,
	major CHAR(100) NOT NULL,
	phoneNumber INT(11) UNSIGNED NOT NULL,
	mbti CHAR(4) NOT NULL,
	snsId CHAR(100) NOT NULL,
	appeal TEXT NOT NULL
);